version: '3.3'

services:
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: girin
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: verystrongpassword
    ports:
      - "27017:27017"
    command: mongod --auth

  mysql:
    image: "mysql:5.7.10"
    container_name: "girin-mysql"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
      MYSQL_DATABASE: "test"

  mariadb:
    image: "mariadb:10.1.16"
    container_name: "girin-mariadb"
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
      MYSQL_DATABASE: "test"

  postgres:
    image: "mdillon/postgis:9.6"
    container_name: "girin-postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "test"

  # mssql:
  #   image: "microsoft/mssql-server-linux:2017-GA"
  #   container_name: "girin-mssql"
  #   ports:
  #     - "1433:1433"
  #   environment:
  #     SA_PASSWORD: "Admin12345"
  #     ACCEPT_EULA: "Y"
